version: "2"
services:
  node:
    image: "node-redux"
    build: .
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    command: npm start
