version: "2"
services:
  node:
    image: "node-redux"
    build: .
    user: "node"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    command: npm start
